spring.application.name=OSApiApplication
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/nsn_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=nsn
spring.datasource.password=gmSenai
spring.jpa.show-sql=True